import json

data = [
    {
      "id": 4987,
      "prjId": "2f67713a-42fa-4dd5-83e5-6b3704496b98",
      "purchaseName": "徐州市五山公园一期工程采购单",
      "endDate": "2019-02-23 19:00:00",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "1045",
      "createDate": "2019-02-22 10:05:39",
      "approvedTime": "2019-02-22",
      "introduce": "",
      "companyId": 118,
      "approved": 3,
      "quoteCount": None,
      "companyName": "大千生态环境集团股份有限公司",
      "districtName": "江苏省徐州市云龙区",
      "districtCode": "320303",
      "status": 0,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "叶琰",
      "buyerTel": "15755055879",
      "dbhMeasure": "130",
      "dijingMeasure": "30",
      "purchasePlants": "火炬树,黄栌",
      "plantsNames": [
        "火炬树",
        "黄栌"
      ],
      "purchaseNo": "PP201902220001",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 0,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 0,
      "isHandinMargin": 0,
      "linkUserId": None,
      "userName": "王妍琪",
      "purchaseType": None,
      "purchaseNameNo": "徐州****采购单(PP201902220001)",
      "isMoreMonth": 0,
      "indexPurchaseDetailList": None,
      "isCanQuote": 1,
      "isWhole": 0,
      "else2": "<p><span>货到交货地点经甲方验收合格后，次月支付10%，三个月后支付至30%，次年农历春节前支付至60%，次年年底前支付至100%，货款均不计利息。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "江苏省徐州市云龙区九七医院向北",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 57,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "0"
    },
    {
      "id": 4986,
      "prjId": "3e5bc668-a2d5-4105-9194-669f3975abbc",
      "purchaseName": "宿迁市沙滩公园总承包（EPC）项目采购单",
      "endDate": "2019-02-24 23:59:59",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "1719",
      "createDate": "2019-02-21 09:52:47",
      "approvedTime": "2019-02-21",
      "introduce": "",
      "companyId": 118,
      "approved": 3,
      "quoteCount": None,
      "companyName": "大千生态环境集团股份有限公司",
      "districtName": "江苏省宿迁市宿豫区",
      "districtCode": "321311",
      "status": 0,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "王雷",
      "buyerTel": "13770331131",
      "dbhMeasure": "130",
      "dijingMeasure": "30",
      "purchasePlants": "造型黑松,黑松1,黑松2,雪松2,广玉兰,石楠,朴树,栾树1,栾树2,五角枫,乌桕1,乌桕2,旱柳2,中山杉2,日本五针松1,日本五针松2,红枫,山樱花,紫叶李,紫丁香",
      "plantsNames": [
        "造型黑松",
        "黑松1",
        "黑松2",
        "雪松2",
        "广玉兰",
        "石楠",
        "朴树",
        "栾树1",
        "栾树2",
        "五角枫",
        "乌桕1",
        "乌桕2",
        "旱柳2",
        "中山杉2",
        "日本五针松1",
        "日本五针松2",
        "红枫",
        "山樱花",
        "紫叶李",
        "紫丁香"
      ],
      "purchaseNo": "PP201902210002",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 0,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 0,
      "isHandinMargin": 0,
      "linkUserId": None,
      "userName": "王妍琪",
      "purchaseType": None,
      "purchaseNameNo": "宿迁****采购单(PP201902210002)",
      "isMoreMonth": 0,
      "indexPurchaseDetailList": None,
      "isCanQuote": 1,
      "isWhole": 0,
      "else2": "<p><span>货到交货地点经甲方验收合格后，次月支付10%，三个月后支付至30%，次年农历春节前支付至60%，次年年底前支付至100%，货款均不计利息。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "江苏省宿迁市宿豫区/王雷/13770331131",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 57,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "一周内"
    },
    {
      "id": 4985,
      "prjId": "3e5bc668-a2d5-4105-9194-669f3975abbc",
      "purchaseName": "宿迁市沙滩公园总承包（EPC）项目采购单",
      "endDate": "2019-02-24 23:59:59",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "1719",
      "createDate": "2019-02-21 09:49:49",
      "approvedTime": "2019-02-21",
      "introduce": "",
      "companyId": 118,
      "approved": 3,
      "quoteCount": None,
      "companyName": "大千生态环境集团股份有限公司",
      "districtName": "江苏省宿迁市宿豫区",
      "districtCode": "321311",
      "status": 0,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "王雷",
      "buyerTel": "13770331131",
      "dbhMeasure": "130",
      "dijingMeasure": "30",
      "purchasePlants": "红瑞木,锦带花,大花六道木,红果金丝桃,金森女贞,铺地柏,连翘,野蔷薇,紫花地丁,大花萱草,阔叶山麦冬,金鸡菊,扫帚草,狼尾草,银边芒,蒲苇,千屈菜,芦苇,再力花,黄菖蒲,果岭草",
      "plantsNames": [
        "红瑞木",
        "锦带花",
        "大花六道木",
        "红果金丝桃",
        "金森女贞",
        "铺地柏",
        "连翘",
        "野蔷薇",
        "紫花地丁",
        "大花萱草",
        "阔叶山麦冬",
        "金鸡菊",
        "扫帚草",
        "狼尾草",
        "银边芒",
        "蒲苇",
        "千屈菜",
        "芦苇",
        "再力花",
        "黄菖蒲",
        "果岭草"
      ],
      "purchaseNo": "PP201902210001",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 0,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 0,
      "isHandinMargin": 0,
      "linkUserId": None,
      "userName": "王妍琪",
      "purchaseType": None,
      "purchaseNameNo": "宿迁****采购单(PP201902210001)",
      "isMoreMonth": 0,
      "indexPurchaseDetailList": None,
      "isCanQuote": 1,
      "isWhole": 0,
      "else2": "<p><span>货到交货地点经甲方验收合格后，次月支付10%，三个月后支付至30%，次年农历春节前支付至60%，次年年底前支付至100%，货款均不计利息。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "江苏省宿迁市宿豫区/王雷/13770331131",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 57,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "一周内"
    },
    {
      "id": 4984,
      "prjId": "2f67713a-42fa-4dd5-83e5-6b3704496b98",
      "purchaseName": "徐州市五山公园一期工程采购单",
      "endDate": "2019-02-20 19:00:00",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "1045",
      "createDate": "2019-02-19 16:55:25",
      "approvedTime": "2019-02-19",
      "introduce": "",
      "companyId": 118,
      "approved": 3,
      "quoteCount": None,
      "companyName": "大千生态环境集团股份有限公司",
      "districtName": "江苏省徐州市云龙区",
      "districtCode": "320303",
      "status": 0,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "叶琰",
      "buyerTel": "15755055879",
      "dbhMeasure": "130",
      "dijingMeasure": "30",
      "purchasePlants": "美女樱,佛甲草,八宝景天,小兔子狼尾草,花叶芦竹,美丽月见草,金钟,黄馨毛球,紫叶狼尾草,狼尾草,金叶石菖蒲,紫娇花,毛地黄,彩叶杞柳,金丝苔草,千屈菜,千叶蓍,火星花,水果兰,柠檬香茅,慈孝竹",
      "plantsNames": [
        "美女樱",
        "佛甲草",
        "八宝景天",
        "小兔子狼尾草",
        "花叶芦竹",
        "美丽月见草",
        "金钟",
        "黄馨毛球",
        "紫叶狼尾草",
        "狼尾草",
        "金叶石菖蒲",
        "紫娇花",
        "毛地黄",
        "彩叶杞柳",
        "金丝苔草",
        "千屈菜",
        "千叶蓍",
        "火星花",
        "水果兰",
        "柠檬香茅",
        "慈孝竹"
      ],
      "purchaseNo": "PP201902190001",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 0,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 0,
      "isHandinMargin": 0,
      "linkUserId": None,
      "userName": "王妍琪",
      "purchaseType": None,
      "purchaseNameNo": "徐州****采购单(PP201902190001)",
      "isMoreMonth": 0,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>货到交货地点经甲方验收合格后，次月支付10%，三个月后支付至30%，次年农历春节前支付至60%，次年年底前支付至100%，货款均不计利息。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "江苏省徐州云龙区九七医院向北",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 57,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "0"
    },
    {
      "id": 4982,
      "prjId": "e5365abc-fd59-4b16-b126-ed2346d6b133",
      "purchaseName": "生产部（金迪世纪大厦立体绿化项目换苗）采购单",
      "endDate": "2019-02-20 23:59:59",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "326",
      "createDate": "2019-02-18 09:16:49",
      "approvedTime": "2019-02-18",
      "introduce": "1.立体绿化用苗\r\n2.预计用苗时间2019.2.21到货",
      "companyId": 32246,
      "approved": 3,
      "quoteCount": None,
      "companyName": "深圳市铁汉一方环境科技有限公司",
      "districtName": "广东省惠州市博罗县",
      "districtCode": "441322",
      "status": 2,
      "quoteRequire": 1,
      "qualityLevel": None,
      "buyer": "梁秀枝",
      "buyerTel": "13928845035",
      "dbhMeasure": "100",
      "dijingMeasure": "10",
      "purchasePlants": "鸭脚木,鸢尾,花叶鸭脚木,肾蕨",
      "plantsNames": [
        "鸭脚木",
        "鸢尾",
        "花叶鸭脚木",
        "肾蕨"
      ],
      "purchaseNo": "PP201902180001",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 1,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 0,
      "isHandinMargin": 0,
      "linkUserId": None,
      "userName": "张华",
      "purchaseType": None,
      "purchaseNameNo": "生产****采购单(PP201902180001)",
      "isMoreMonth": 0,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>在乙方起苗前，甲方应将货款支付到丙方担保账户（或提供银行保函给丙方作为担保），货到现场验收合格且在双方确认验收结果后，供应商上传发票及发票签收单（或快递单）并达到付款条件后90天内甲方支付至丙方担保账户，并由丙方支付至乙方账户。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "广东省惠州市博罗县茅池岭/梁秀枝/13928845035",
      "companyDeliveryAddress": "/",
      "isTacticOver": 0,
      "tempId": 42,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "2019.2.21"
    },
    {
      "id": 4981,
      "prjId": "8a8ecdbb-d2b1-406a-814b-a9dcba0da08c",
      "purchaseName": "洛阳伊河嵩县城区水生态治理PPP项目采购单",
      "endDate": "2019-02-12 23:59:59",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "31562",
      "createDate": "2019-01-24 12:06:55",
      "approvedTime": "2019-01-24",
      "introduce": "报价需注意，此部分苗木为正月内用苗，落实好正月期间起苗工作。当地苗优先选择。选标时间2019年1月30日。",
      "companyId": 143,
      "approved": 3,
      "quoteCount": None,
      "companyName": "深圳市铁汉生态环境股份有限公司",
      "districtName": "河南省洛阳市嵩县",
      "districtCode": "410325",
      "status": 0,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "苏杭",
      "buyerTel": "18665956201",
      "dbhMeasure": "120",
      "dijingMeasure": "30",
      "purchasePlants": "白皮松,水杉,黄连木,红梅,高杆紫薇,腊梅",
      "plantsNames": [
        "白皮松",
        "水杉",
        "黄连木",
        "红梅",
        "高杆紫薇",
        "腊梅"
      ],
      "purchaseNo": "PP201901240003",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 1,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 1,
      "isHandinMargin": 1,
      "linkUserId": None,
      "userName": "林舒情 ",
      "purchaseType": None,
      "purchaseNameNo": "洛阳****采购单(PP201901240003)",
      "isMoreMonth": 0,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>在乙方起苗前，甲方应将货款支付到丙方担保账户（或提供银行保函给丙方作为担保），货到现场验收合格且在双方确认验收结果后，供应商上传发票及发票签收单（或快递单）并达到付款条件后90天内甲方支付至丙方担保账户，并由丙方支付至乙方账户。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "河南省洛阳市嵩县/苏杭/18665956201",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 42,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "2019年2月20日"
    },
    {
      "id": 4979,
      "prjId": "6f597c03-3671-4031-bbe9-e45e668156e7",
      "purchaseName": "中山港口西街联创基地15分全冠香樟地苗采购采购单",
      "endDate": "2019-01-25 23:59:59",
      "twoEndDate": None,
      "invoiceType": "4",
      "creater": "68174",
      "createDate": "2019-01-24 08:26:13",
      "approvedTime": "2019-01-24",
      "introduce": "全冠米径15分香樟地苗，土球80公分，分枝点1.8-2.5米，枝条均匀（4条枝及以上），冠幅饱满，无破皮断枝偏冠情况，装车打掉叶片，货到付款。",
      "companyId": 66250,
      "approved": 3,
      "quoteCount": None,
      "companyName": "中山市德泓生态园林科技有限公司",
      "districtName": "广东省中山市",
      "districtCode": "442000",
      "status": 0,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "杨海龙",
      "buyerTel": "18928100866",
      "dbhMeasure": "100",
      "dijingMeasure": "10",
      "purchasePlants": "全冠香樟地苗",
      "plantsNames": [
        "全冠香樟地苗"
      ],
      "purchaseNo": "PP201901240001",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 0,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 0,
      "isHandinMargin": 0,
      "linkUserId": None,
      "userName": "何斯远",
      "purchaseType": None,
      "purchaseNameNo": "中山****采购单(PP201901240001)",
      "isMoreMonth": 0,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>在乙方起苗前，甲方应将货款支付到丙方担保账户（或提供银行保函给丙方作为担保），货到现场验收合格且在双方确认验收结果后，供应商上传发票及发票签收单（或快递单）并达到付款条件后90天内甲方支付至丙方担保账户，并由丙方支付至乙方账户。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "北京市市辖区东城区港口镇西街小学旁联创园林/杨海龙/18928100866",
      "companyDeliveryAddress": "/",
      "isTacticOver": 0,
      "tempId": 42,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "2019/1/27"
    },
    {
      "id": 4978,
      "prjId": "547c15ff-a869-45fd-a043-b3988213a585",
      "purchaseName": "泰和县马市特色小镇PPP项目采购单",
      "endDate": "2019-01-23 23:59:59",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "54581",
      "createDate": "2019-01-22 11:46:26",
      "approvedTime": "2019-01-22",
      "introduce": "",
      "companyId": 118,
      "approved": 3,
      "quoteCount": None,
      "companyName": "大千生态环境集团股份有限公司",
      "districtName": "江西省吉安市泰和县",
      "districtCode": "360826",
      "status": 2,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "江杰",
      "buyerTel": "13807065870",
      "dbhMeasure": "130",
      "dijingMeasure": "30",
      "purchasePlants": "三色堇,石竹,羽衣甘蓝",
      "plantsNames": [
        "三色堇",
        "石竹",
        "羽衣甘蓝"
      ],
      "purchaseNo": "PP201901220002",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 0,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 1,
      "isHandinMargin": 0,
      "linkUserId": None,
      "userName": "王妍琪",
      "purchaseType": None,
      "purchaseNameNo": "泰和****采购单(PP201901220002)",
      "isMoreMonth": 0,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>货到交货地点经甲方验收合格后，次月支付10%，三个月后支付至30%，次年农历春节前支付至60%，次年年底前支付至100%，货款均不计利息。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "江西省吉安市泰和县泰和县蜀口洲风景区/杨义广/13776666898",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 57,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "9.6m货车",
      "firstBatchPlantToMarket": "2019.1.25"
    },
    {
      "id": 4976,
      "prjId": "204decb2-9d9e-41c9-8e4f-5e60b644fde3",
      "purchaseName": "徐州市轨道交通线网控中心项目景观绿化工程采购单",
      "endDate": "2019-01-22 19:00:00",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "1045",
      "createDate": "2019-01-21 18:23:52",
      "approvedTime": "2019-01-21",
      "introduce": "",
      "companyId": 118,
      "approved": 3,
      "quoteCount": None,
      "companyName": "大千生态环境集团股份有限公司",
      "districtName": "江苏省徐州市云龙区",
      "districtCode": "320303",
      "status": 2,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "叶琰",
      "buyerTel": "15755055879",
      "dbhMeasure": "130",
      "dijingMeasure": "30",
      "purchasePlants": "海桐球,金森女贞球,红叶石楠球,高杆女贞,樱花,鸡爪槭,红叶石楠小苗,金边黄杨小苗,红叶石楠篱,丛生紫薇,果岭草草坪",
      "plantsNames": [
        "海桐球",
        "金森女贞球",
        "红叶石楠球",
        "高杆女贞",
        "樱花",
        "鸡爪槭",
        "红叶石楠小苗",
        "金边黄杨小苗",
        "红叶石楠篱",
        "丛生紫薇",
        "果岭草草坪"
      ],
      "purchaseNo": "PP201901210003",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 0,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 0,
      "isHandinMargin": 0,
      "linkUserId": None,
      "userName": "王妍琪",
      "purchaseType": None,
      "purchaseNameNo": "徐州****采购单(PP201901210003)",
      "isMoreMonth": 0,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>货到交货地点经甲方验收合格后，次月支付10%，三个月后支付至30%，次年农历春节前支付至60%，次年年底前支付至100%，货款均不计利息。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 57,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "0"
    },
    {
      "id": 4969,
      "prjId": "b12715e1-6342-4c7b-bafc-143a4d91b8cd",
      "purchaseName": "陕西省黄土高原山水林田湖生态保护修复试点工程采购单",
      "endDate": "2019-01-24 23:59:59",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "45413",
      "createDate": "2019-01-17 17:54:01",
      "approvedTime": "2019-01-18",
      "introduce": "1.苗源地主要以距离陕西宜君不超过350公里半径为优选。\r\n2.油松必须选择苗源为陕西铜川以北的苗木，主要优选陕西北部，甘肃庆阳，山西临汾。",
      "companyId": 143,
      "approved": 3,
      "quoteCount": None,
      "companyName": "深圳市铁汉生态环境股份有限公司",
      "districtName": "陕西省铜川市宜君县",
      "districtCode": "610222",
      "status": 0,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "康军警",
      "buyerTel": "18792428796",
      "dbhMeasure": "130",
      "dijingMeasure": "10",
      "purchasePlants": "油松,五角枫,黄栌,香花槐,刺槐,栎树,连翘,柠条,连翘小,紫穗槐,牡丹木槿,美人梅,桧柏,爬山虎,侧柏,国槐,红叶李,榆叶梅,黄蔷薇,核桃,垂柳,大叶黄杨",
      "plantsNames": [
        "油松",
        "五角枫",
        "黄栌",
        "香花槐",
        "刺槐",
        "栎树",
        "连翘",
        "柠条",
        "连翘小",
        "紫穗槐",
        "牡丹木槿",
        "美人梅",
        "桧柏",
        "爬山虎",
        "侧柏",
        "国槐",
        "红叶李",
        "榆叶梅",
        "黄蔷薇",
        "核桃",
        "垂柳",
        "大叶黄杨"
      ],
      "purchaseNo": "PP201901170003",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 1,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 1,
      "isHandinMargin": 1,
      "linkUserId": None,
      "userName": "林舒情 ",
      "purchaseType": None,
      "purchaseNameNo": "陕西****采购单(PP201901170003)",
      "isMoreMonth": 0,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>在乙方起苗前，甲方应将货款支付到丙方担保账户（或提供银行保函给丙方作为担保），货到现场验收合格且在双方确认验收结果后，供应商上传发票及发票签收单（或快递单）并达到付款条件后90天内甲方支付至丙方担保账户，并由丙方支付至乙方账户。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "陕西省铜川市宜君县/马晓炜/18681920666",
      "companyDeliveryAddress": "/",
      "isTacticOver": 0,
      "tempId": 42,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "运输车辆限制9.6m以下。",
      "firstBatchPlantToMarket": "预计2019年2月28日"
    },
    {
      "id": 4965,
      "prjId": "d4c16e92-5a14-41d3-8487-8100326b252c",
      "purchaseName": "珠海市斗门区黑臭河涌水生态修复PPP项目采购单",
      "endDate": "2019-02-11 23:59:59",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "67383",
      "createDate": "2019-01-17 09:50:51",
      "approvedTime": "2019-01-17",
      "introduce": "",
      "companyId": 143,
      "approved": 3,
      "quoteCount": None,
      "companyName": "深圳市铁汉生态环境股份有限公司",
      "districtName": "广东省珠海市斗门区",
      "districtCode": "440403",
      "status": 2,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "冯志锋",
      "buyerTel": "18027178372",
      "dbhMeasure": "100",
      "dijingMeasure": "10",
      "purchasePlants": "落羽杉",
      "plantsNames": [
        "落羽杉"
      ],
      "purchaseNo": "PP201901170001",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 1,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 1,
      "isHandinMargin": 1,
      "linkUserId": None,
      "userName": "林舒情 ",
      "purchaseType": None,
      "purchaseNameNo": "珠海****采购单(PP201901170001)",
      "isMoreMonth": 0,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>在乙方起苗前，甲方应将货款支付到丙方担保账户（或提供银行保函给丙方作为担保），货到现场验收合格且在双方确认验收结果后，供应商上传发票及发票签收单（或快递单）并达到付款条件后90天内甲方支付至丙方担保账户，并由丙方支付至乙方账户。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "广东省珠海市斗门区珠海市斗门区井岸镇新堂村住宅新区9巷2号（铁汉生态）3楼/郭东福/13923876506",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 42,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "9.6米·（含9.6米以下）",
      "firstBatchPlantToMarket": "2019.2.25"
    },
    {
      "id": 4973,
      "prjId": "d8fbc777-abeb-42a4-bfd1-8fe661a0c9f1",
      "purchaseName": "高淳项目采购单",
      "endDate": "2019-01-20 23:59:59",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "62122",
      "createDate": "2019-01-19 16:56:19",
      "approvedTime": "2019-01-19",
      "introduce": "",
      "companyId": 118,
      "approved": 3,
      "quoteCount": None,
      "companyName": "大千生态环境集团股份有限公司",
      "districtName": "江苏省南京市高淳县",
      "districtCode": "320125",
      "status": 2,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "孙中阳",
      "buyerTel": "18652065302",
      "dbhMeasure": "130",
      "dijingMeasure": "30",
      "purchasePlants": "碧桃,樱花,北美海棠,桂花,美人蕉,水生鸢尾,千屈菜,再力花,黄馨,欧月,福禄考,兰花三七,石竹,美女樱,细叶麦冬,混播黑麦草",
      "plantsNames": [
        "碧桃",
        "樱花",
        "北美海棠",
        "桂花",
        "美人蕉",
        "水生鸢尾",
        "千屈菜",
        "再力花",
        "黄馨",
        "欧月",
        "福禄考",
        "兰花三七",
        "石竹",
        "美女樱",
        "细叶麦冬",
        "混播黑麦草"
      ],
      "purchaseNo": "PP201901190003",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 0,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 1,
      "isHandinMargin": 0,
      "linkUserId": None,
      "userName": "王妍琪",
      "purchaseType": None,
      "purchaseNameNo": "高淳****采购单(PP201901190003)",
      "isMoreMonth": 1,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>货到交货地点经甲方验收合格后，次月支付10%，三个月后支付至30%，次年农历春节前支付至60%，次年年底前支付至100%，货款均不计利息。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "江苏省南京市高淳县/孙中阳/18652065302",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 57,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "等通知"
    },
    {
      "id": 4964,
      "prjId": "80c80443-4140-48f8-887a-376b21ff365a",
      "purchaseName": "高青县天鹅湖国际慢城PPP项目采购单",
      "endDate": "2019-01-21 23:59:59",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "48496",
      "createDate": "2019-01-16 14:55:09",
      "approvedTime": "2019-01-17",
      "introduce": "",
      "companyId": 143,
      "approved": 3,
      "quoteCount": None,
      "companyName": "深圳市铁汉生态环境股份有限公司",
      "districtName": "山东省淄博市高青县",
      "districtCode": "370322",
      "status": 2,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "利剑平",
      "buyerTel": "13763241007",
      "dbhMeasure": "120",
      "dijingMeasure": "10",
      "purchasePlants": ".迎春,.金叶女贞,野花种子,造型小叶女贞,.金鸡菊,.粉黛乱子草,狼尾草,.红叶石楠",
      "plantsNames": [
        ".迎春",
        ".金叶女贞",
        "野花种子",
        "造型小叶女贞",
        ".金鸡菊",
        ".粉黛乱子草",
        "狼尾草",
        ".红叶石楠"
      ],
      "purchaseNo": "PP201901160001",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 1,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 1,
      "isHandinMargin": 1,
      "linkUserId": None,
      "userName": "林舒情 ",
      "purchaseType": None,
      "purchaseNameNo": "高青****采购单(PP201901160001)",
      "isMoreMonth": 1,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>在乙方起苗前，甲方应将货款支付到丙方担保账户（或提供银行保函给丙方作为担保），货到现场验收合格且在双方确认验收结果后，供应商上传发票及发票签收单（或快递单）并达到付款条件后90天内甲方支付至丙方担保账户，并由丙方支付至乙方账户。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "山东省滨州市滨城区/彭海林/13637326431",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 42,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "2019.1.22"
    },
    {
      "id": 4963,
      "prjId": "5fe0fc80-470a-45c3-8304-a33931d40c19",
      "purchaseName": "湖北省黄石市大冶湖奥体中心南侧绿化、中央景观带（含人工水体）项目采购单",
      "endDate": "2019-01-21 23:59:59",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "376",
      "createDate": "2019-01-15 16:27:03",
      "approvedTime": "2019-01-16",
      "introduce": "",
      "companyId": 143,
      "approved": 3,
      "quoteCount": None,
      "companyName": "深圳市铁汉生态环境股份有限公司",
      "districtName": "湖北省黄石市大冶市",
      "districtCode": "420281",
      "status": 0,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "闫殊以",
      "buyerTel": "15172717750",
      "dbhMeasure": "130",
      "dijingMeasure": "20",
      "purchasePlants": ".鸡爪槭A,.鸡爪槭B,.红梅A,.日本红枫A,.垂丝海棠A,.贴梗海棠A,皇红醉鱼草,.乌桕B,银杏B,.栾树B,.香樟B,.朴树A,吉祥草,.小叶扶芳藤,.小叶栀子,.南天竹,.毛鹃,.栀子花,.瓜子黄杨,.八角金盘,.细叶麦冬,.法国冬青",
      "plantsNames": [
        ".鸡爪槭A",
        ".鸡爪槭B",
        ".红梅A",
        ".日本红枫A",
        ".垂丝海棠A",
        ".贴梗海棠A",
        "皇红醉鱼草",
        ".乌桕B",
        "银杏B",
        ".栾树B",
        ".香樟B",
        ".朴树A",
        "吉祥草",
        ".小叶扶芳藤",
        ".小叶栀子",
        ".南天竹",
        ".毛鹃",
        ".栀子花",
        ".瓜子黄杨",
        ".八角金盘",
        ".细叶麦冬",
        ".法国冬青"
      ],
      "purchaseNo": "PP201901150003",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 1,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 1,
      "isHandinMargin": 1,
      "linkUserId": None,
      "userName": "林舒情 ",
      "purchaseType": None,
      "purchaseNameNo": "湖北****采购单(PP201901150003)",
      "isMoreMonth": 1,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>在乙方起苗前，甲方应将货款支付到丙方担保账户（或提供银行保函给丙方作为担保），货到现场验收合格且在双方确认验收结果后，供应商上传发票及发票签收单（或快递单）并达到付款条件后90天内甲方支付至丙方担保账户，并由丙方支付至乙方账户。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "湖北省黄石市大冶市/闫殊以/15172717750",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 42,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "2019-2-20"
    },
    {
      "id": 4962,
      "prjId": "283dc442-7769-40b7-b952-105b57680a36",
      "purchaseName": "湖南省临湘市长安文化创意园建设PPP项目采购单",
      "endDate": "2019-01-18 23:59:59",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "1957",
      "createDate": "2019-01-15 15:39:23",
      "approvedTime": "2019-01-15",
      "introduce": "苗木要求是精品（可以是裸根苗）",
      "companyId": 143,
      "approved": 3,
      "quoteCount": None,
      "companyName": "深圳市铁汉生态环境股份有限公司",
      "districtName": "湖南省岳阳市临湘市",
      "districtCode": "430682",
      "status": 2,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "吴超群",
      "buyerTel": "18751720719",
      "dbhMeasure": "100",
      "dijingMeasure": "10",
      "purchasePlants": ".红继木球,海桐球A,金边黄杨A,山茶B,.丝兰,.马尼拉草",
      "plantsNames": [
        ".红继木球",
        "海桐球A",
        "金边黄杨A",
        "山茶B",
        ".丝兰",
        ".马尼拉草"
      ],
      "purchaseNo": "PP201901150002",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 1,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 1,
      "isHandinMargin": 1,
      "linkUserId": None,
      "userName": "林舒情 ",
      "purchaseType": None,
      "purchaseNameNo": "湖南****采购单(PP201901150002)",
      "isMoreMonth": 1,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>在乙方起苗前，甲方应将货款支付到丙方担保账户（或提供银行保函给丙方作为担保），货到现场验收合格且在双方确认验收结果后，供应商上传发票及发票签收单（或快递单）并达到付款条件后90天内甲方支付至丙方担保账户，并由丙方支付至乙方账户。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "湖南省岳阳市临湘市湖南省临湘市五尖山森林公园公园路三角坪铁汉项目部/徐小龙/15768898768",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 42,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "2019年1月19"
    },
    {
      "id": 4961,
      "prjId": "1851ec5d-bd03-495c-814f-f42b58e8595f",
      "purchaseName": "福建省泉州市晋江下游生态整治工程（一期）项目 （黄龙大桥至溪漧桥提升段）设计施工一体化采购单",
      "endDate": "2019-01-17 22:59:59",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "48330",
      "createDate": "2019-01-15 09:14:41",
      "approvedTime": "2019-01-15",
      "introduce": "",
      "companyId": 143,
      "approved": 3,
      "quoteCount": None,
      "companyName": "深圳市铁汉生态环境股份有限公司",
      "districtName": "北京市市辖区东城区",
      "districtCode": "110101",
      "status": 0,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "顾小艺",
      "buyerTel": "15011886369",
      "dbhMeasure": "120",
      "dijingMeasure": "30",
      "purchasePlants": ".黄金叶,.亮叶朱蕉,.粉花翠卢莉,.麦冬",
      "plantsNames": [
        ".黄金叶",
        ".亮叶朱蕉",
        ".粉花翠卢莉",
        ".麦冬"
      ],
      "purchaseNo": "PP201901150001",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 1,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 1,
      "isHandinMargin": 1,
      "linkUserId": None,
      "userName": "林舒情 ",
      "purchaseType": None,
      "purchaseNameNo": "福建****采购单(PP201901150001)",
      "isMoreMonth": 1,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>在乙方起苗前，甲方应将货款支付到丙方担保账户（或提供银行保函给丙方作为担保），货到现场验收合格且在双方确认验收结果后，供应商上传发票及发票签收单（或快递单）并达到付款条件后90天内甲方支付至丙方担保账户，并由丙方支付至乙方账户。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "福建省泉州市晋江市/顾小艺/15011886369",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 42,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "/"
    },
    {
      "id": 4959,
      "prjId": "4731ddaa-e366-4913-a9ef-5924b1841b5e",
      "purchaseName": "世茂.太白国风雅颂示范区项目采购单",
      "endDate": "2019-01-18 23:59:59",
      "twoEndDate": None,
      "invoiceType": "4",
      "creater": "66643",
      "createDate": "2019-01-13 21:07:57",
      "approvedTime": "2019-01-13",
      "introduce": "发票类型按供货商自己公司决定2.到场苗木不合格，需更换",
      "companyId": 49,
      "approved": 3,
      "quoteCount": None,
      "companyName": "北京星河绿源园林苗木有限公司",
      "districtName": "陕西省宝鸡市眉县",
      "districtCode": "610326",
      "status": 0,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "曹希洋",
      "buyerTel": "18894001036",
      "dbhMeasure": "100",
      "dijingMeasure": "10",
      "purchasePlants": "国槐C,日本晚樱,紫玉兰,鸡爪槭A,刚竹,木槿A,丛生紫薇C,丛生石楠A,丛生石楠B,海桐球A,海桐球B,红叶石楠球A,红叶石楠球B,毛鹃球A,毛鹃球B,金森女贞球,瓜子黄杨,金森女贞,金叶女贞,红叶石楠,北海道黄杨柱,日本麦冬,金边吊兰,天竺葵,朱蕉,南天竹,花叶玉簪,睡莲,夏鹃,海桐A,海桐B,八角金盘,金叶风箱果,龙血树,变叶木,时令草花,佛甲草,树皮",
      "plantsNames": [
        "国槐C",
        "日本晚樱",
        "紫玉兰",
        "鸡爪槭A",
        "刚竹",
        "木槿A",
        "丛生紫薇C",
        "丛生石楠A",
        "丛生石楠B",
        "海桐球A",
        "海桐球B",
        "红叶石楠球A",
        "红叶石楠球B",
        "毛鹃球A",
        "毛鹃球B",
        "金森女贞球",
        "瓜子黄杨",
        "金森女贞",
        "金叶女贞",
        "红叶石楠",
        "北海道黄杨柱",
        "日本麦冬",
        "金边吊兰",
        "天竺葵",
        "朱蕉",
        "南天竹",
        "花叶玉簪",
        "睡莲",
        "夏鹃",
        "海桐A",
        "海桐B",
        "八角金盘",
        "金叶风箱果",
        "龙血树",
        "变叶木",
        "时令草花",
        "佛甲草",
        "树皮"
      ],
      "purchaseNo": "PP201901130001",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 1,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 0,
      "isHandinMargin": 0,
      "linkUserId": None,
      "userName": "米彦杰",
      "purchaseType": None,
      "purchaseNameNo": "世茂****采购单(PP201901130001)",
      "isMoreMonth": 1,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>在乙方起苗前，甲方应将货款支付到丙方担保账户（或提供银行保函给丙方作为担保），货到现场验收合格且在双方确认验收结果后，供应商上传发票及发票签收单（或快递单）并达到付款条件后90天内甲方支付至丙方担保账户，并由丙方支付至乙方账户。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "陕西省宝鸡市眉县/曹希洋/18894001036",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 42,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "2019年2月"
    },
    {
      "id": 4958,
      "prjId": "2f67713a-42fa-4dd5-83e5-6b3704496b98",
      "purchaseName": "徐州市五山公园一期工程采购单",
      "endDate": "2019-01-13 20:00:00",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "1045",
      "createDate": "2019-01-12 19:17:42",
      "approvedTime": "2019-01-12",
      "introduce": "",
      "companyId": 118,
      "approved": 3,
      "quoteCount": None,
      "companyName": "大千生态环境集团股份有限公司",
      "districtName": "江苏省徐州市云龙区",
      "districtCode": "320303",
      "status": 2,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "叶琰",
      "buyerTel": "15755055879",
      "dbhMeasure": "130",
      "dijingMeasure": "30",
      "purchasePlants": "女贞,桂花B,桂花A,小叶女贞球,樱花B,樱花A,海桐球,红叶石楠球,特选樱花,金叶女贞球A,金叶女贞球B,紫玉兰A,紫玉兰B,白皮松B,鸡爪槭A,丛生紫薇,麦冬,红叶石楠篱,菲白竹,粉花绣线菊,金边黄杨小苗,红叶石楠小苗,南天竹小苗,果岭草草坪",
      "plantsNames": [
        "女贞",
        "桂花B",
        "桂花A",
        "小叶女贞球",
        "樱花B",
        "樱花A",
        "海桐球",
        "红叶石楠球",
        "特选樱花",
        "金叶女贞球A",
        "金叶女贞球B",
        "紫玉兰A",
        "紫玉兰B",
        "白皮松B",
        "鸡爪槭A",
        "丛生紫薇",
        "麦冬",
        "红叶石楠篱",
        "菲白竹",
        "粉花绣线菊",
        "金边黄杨小苗",
        "红叶石楠小苗",
        "南天竹小苗",
        "果岭草草坪"
      ],
      "purchaseNo": "PP201901120002",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 0,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 0,
      "isHandinMargin": 0,
      "linkUserId": None,
      "userName": "王妍琪",
      "purchaseType": None,
      "purchaseNameNo": "徐州****采购单(PP201901120002)",
      "isMoreMonth": 1,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>货到交货地点经甲方验收合格后，次月支付10%，三个月后支付至30%，次年农历春节前支付至60%，次年年底前支付至100%，货款均不计利息。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "江苏省徐州市云龙区徐州云龙区九七医院向北",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 57,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "0"
    },
    {
      "id": 4957,
      "prjId": "aa6269ed-7898-404c-94c8-cc1e5c3b31ed",
      "purchaseName": "百花湖滨湖花廊 项目采购单",
      "endDate": "2019-01-16 23:59:59",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "61639",
      "createDate": "2019-01-12 12:22:10",
      "approvedTime": "2019-01-12",
      "introduce": "",
      "companyId": 31468,
      "approved": 3,
      "quoteCount": None,
      "companyName": "铁汉山艺环境建设有限公司",
      "districtName": "贵州省贵阳市清镇市",
      "districtCode": "520181",
      "status": 0,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "黄韬",
      "buyerTel": "13985869965",
      "dbhMeasure": "100",
      "dijingMeasure": "10",
      "purchasePlants": "鸡爪槭,红枫,红叶石楠球,红花继木球,春鹃,茶梅,南天竹,本地多红（杜鹃）,三角梅,杜鹃球,大叶黄杨,丰花月季,红花檵木,金叶女贞,柳叶马鞭草花种,鼠尾草花种,波斯菊花种,大花金鸡菊花种,黄金菊花种,美女樱花种",
      "plantsNames": [
        "鸡爪槭",
        "红枫",
        "红叶石楠球",
        "红花继木球",
        "春鹃",
        "茶梅",
        "南天竹",
        "本地多红（杜鹃）",
        "三角梅",
        "杜鹃球",
        "大叶黄杨",
        "丰花月季",
        "红花檵木",
        "金叶女贞",
        "柳叶马鞭草花种",
        "鼠尾草花种",
        "波斯菊花种",
        "大花金鸡菊花种",
        "黄金菊花种",
        "美女樱花种"
      ],
      "purchaseNo": "PP201901120001",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 1,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 1,
      "isHandinMargin": 1,
      "linkUserId": None,
      "userName": "邱钰媛",
      "purchaseType": None,
      "purchaseNameNo": "百花****采购单(PP201901120001)",
      "isMoreMonth": 1,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>在乙方起苗前，甲方应将货款支付到丙方担保账户（或提供银行保函给丙方作为担保），货到现场验收合格且在双方确认验收结果后，供应商上传发票及发票签收单（或快递单）并达到付款条件后90天内甲方支付至丙方担保账户，并由丙方支付至乙方账户。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "贵州省贵阳市清镇市/黄韬/13985869965",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 42,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "2019年3月"
    },
    {
      "id": 4955,
      "prjId": "1851ec5d-bd03-495c-814f-f42b58e8595f",
      "purchaseName": "福建省泉州市晋江下游生态整治工程（一期）项目 （黄龙大桥至溪漧桥提升段）设计施工一体化采购单",
      "endDate": "2019-01-13 23:59:59",
      "twoEndDate": None,
      "invoiceType": "3",
      "creater": "45413",
      "createDate": "2019-01-10 17:54:26",
      "approvedTime": "2019-01-10",
      "introduce": "",
      "companyId": 143,
      "approved": 3,
      "quoteCount": None,
      "companyName": "深圳市铁汉生态环境股份有限公司",
      "districtName": "福建省泉州市市辖区",
      "districtCode": "350501",
      "status": 2,
      "quoteRequire": 2,
      "qualityLevel": None,
      "buyer": "顾小艺",
      "buyerTel": "15011886369",
      "dbhMeasure": "130",
      "dijingMeasure": "30",
      "purchasePlants": "粉花翠卢莉,麦冬,海芋,散尾葵,常春藤,三角梅(水红）,琴丝竹B,雪茄花,鸳鸯茉莉,琴叶珊瑚,粉花夹竹桃,马尼拉,大叶油草,紫叶狼尾草,美人蕉",
      "plantsNames": [
        "粉花翠卢莉",
        "麦冬",
        "海芋",
        "散尾葵",
        "常春藤",
        "三角梅(水红）",
        "琴丝竹B",
        "雪茄花",
        "鸳鸯茉莉",
        "琴叶珊瑚",
        "粉花夹竹桃",
        "马尼拉",
        "大叶油草",
        "紫叶狼尾草",
        "美人蕉"
      ],
      "purchaseNo": "PP201901100002",
      "isTwoQuote": 0,
      "isPlantformChoose": 1,
      "isPlantformPay": 1,
      "isColsePurchaseLook": 0,
      "authority": None,
      "isReleasePlant": 0,
      "isUploadPlantPhoto": 1,
      "isHandinMargin": 1,
      "linkUserId": None,
      "userName": "林舒情 ",
      "purchaseType": None,
      "purchaseNameNo": "福建****采购单(PP201901100002)",
      "isMoreMonth": 1,
      "indexPurchaseDetailList": None,
      "isCanQuote": 0,
      "isWhole": 0,
      "else2": "<p><span>在乙方起苗前，甲方应将货款支付到丙方担保账户（或提供银行保函给丙方作为担保），货到现场验收合格且在双方确认验收结果后，供应商上传发票及发票签收单（或快递单）并达到付款条件后90天内甲方支付至丙方担保账户，并由丙方支付至乙方账户。</span></p>",
      "paymentDay": 90,
      "projectDeliveryAddress": "福建省泉州市晋江市/顾小艺/15011886369",
      "companyDeliveryAddress": "",
      "isTacticOver": 0,
      "tempId": 42,
      "bidStatus": None,
      "purchaseState": None,
      "carType": "无",
      "firstBatchPlantToMarket": "/"
    }
  ]

class ItaoOrder():
    def __init__(self,d):
        self.__dict__ = d

def convert():
    print(len(data))

convert()